### ISSUE TITLE
Refactor for 1.0

### ISSUE THREAD

**Issue by blakeembrey** [jonschlinkert/uniqueid#2]
Would you consider a refactor for 1.0 that would make this module more re-usable? Instead of having a reset, weird options, etc. it could export a function that you set up with these options. Then just call that function to increment each time. When you want to reset, just make a new function.

I'd be more than happy to make the changes and releases for you, as I noticed it's years old :smile:

**Comment by jonschlinkert** [comment]
that would be great! thanks!

> as I noticed it's years old

lol yeah, I've said this before but sometimes I cringe when I see old code I wrote.

**Comment by jonschlinkert** [comment]
added you as a collab here and on npm. I completely trust your judgement!

**Comment by blakeembrey** [comment]
@jonschlinkert Any features you just can't lose? I know there's only like three, but still curious before I change stuff. Otherwise I'll just go simple.

**Comment by jonschlinkert** [comment]
Feel free to make whatever changes you think make sense. thanks for asking!
